### ISSUE TITLE
Restore Browser Global

### ISSUE THREAD

**Issue by ghost** [helgoboss/iota-observable#2]
I was very pleased to discover iota Observable and use it immediately with Rivets.js for an existing large JS project, but I was disappointed --- really :( --- to find out you've disabled its use in a Browser-Global way.

I think I understand why you made this decision. On the other hand, you may be limiting the use/adoption of your library by doing so, because there are still a lot of JS developers like myself who have not yet found the time to ride the AMD bandwagon.

Please restore support for Browser-Global if you can.

**Comment by helgoboss** [comment]
I knew this issue would come up sooner or later :) Unfortunately, at release time I didn't know how to support all of the 3 major usage scenarios at the same time (Node, AMD and browser globals). Recently, I discovered the UMD pattern. That should do the trick. I will integrate it as soon as possible.

**Comment by helgoboss** [comment]
Fixed. If no AMD or Node environment is detected, a global variable "Observable" is available.
