### ISSUE TITLE
jQuery isn't needed

### ISSUE THREAD

**Issue by gaydenko** [helgoboss/iota-observable#3]
"With Rivets (CoffeeScript)" chapter from README says: "Needs jQuery and Rivets Iota Observable Adapter". I have looked in rivets' util.coffee and guess Rivets doesn't require jQuery: raw DOM element can be bound. So, words about needing jQuery can be misunderstood as far as all participants are jQuery-free :)

**Comment by helgoboss** [comment]
Thanks for the hint. I changed the wording on both GitHub and the website.
